[package]
name = "selfbot"
version = "0.1.0"
edition = "2024"

[dependencies]
serenity = { version = "0.11", features = ["client", "gateway", "rustls_backend", "model"] } 
reqwest = { version = "0.11", features = ["json"] }
